Brian Holliday<br/>
Professor Thiel<br/>
Stochastic Models<br/>
10 December 2019<br/>

Project #3

Abstract:<br/>

This project provides a simulation for the childrens board game shoots and ladders on a 5X5 square. In this game shoots and ladders connect to points on the board from which player can transition. If a player lands on a ladder they will climb up to the other end point bringing them closer to the end point. If a player lands on a shoot they will slide down to other end point of the shoot.<br/>

The first part of the code is too show what the potential game board looks. This game board is 5X5 and runs from 1 - 25. Next, we use the four function to creates four lists that will have the set of the points for our 2 chuts and 2 ladders. We start with an empty list. The function will generate ten random numbers between 1 - 13 and will only add it to the list if the generated number is not in the list. We only use the first four elements in the list. For two of the numbers, we will return the number and the same number plus ten for a big chut/ladder. For the other two, we will return the number and the number plus 5 for the small chut/ladder.<br/>

In the function SandL(), we call on the four() function to get our chuts and ladders. A six sided dice is rolled and the player will move that value on the board. If the player lands at the bottom of a ladder then they will automatically we transported to the top of the ladder. If the player lands at the top chut they will be transported to the bottom of the chut.<br/> 

We use a Monte Carlo method to find the average number of turns to finish this board. We do this by returning the turns in the SandL() function. We get that it is about an average of 12 turns to finish the game. This is futher shown by the histogram. We see that most of the finishes happen between 5 and 20 rolls. 

In [87]:
import numpy as np
import matplotlib.pyplot as plt
import random

Game Board

In [88]:
num = 25
gameboard = np.zeros(25)
for i in range(len(gameboard)):
    gameboard[i] = num
    num = num - 1
gameboard = gameboard.reshape(5,5)
gameboard[4] = gameboard[4][::-1]
gameboard[2] = gameboard[2][::-1]
gameboard[0] = gameboard[0][::-1]
gameboard

array([[21., 22., 23., 24., 25.],
       [20., 19., 18., 17., 16.],
       [11., 12., 13., 14., 15.],
       [10.,  9.,  8.,  7.,  6.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [89]:
def four():
    list = []
    for i in range(10):
        r = random.randint(1,14)
        if r not in list:#To make sure the chuts and ladders are not same points
            list.append(r)
    list = list[0:4]
    #+5 are little chuts/ladders, +10 are big chuts/ladders
    return [list[0],list[0] + 5], [list[1],list[1] + 10], [list[2],list[2] + 5], [list[3], list[3] + 10]

In [90]:
def SandL():
    chut1,chut2,ladder1,ladder2 = four() #Function to get random chuts and ladders
    P = []
    position = 0
    turns = 0
    for i in range(10000):
        turns = turns + 1
        position = position + np.random.randint(1,7)
        if position == chut1[1]:
            position = chut1[0]
        if position == chut2[1]:
            position = chut2[0]
        if position == ladder1[0]:
            position = ladder1[1]
        if position == ladder2[0]:
            position = ladder2[1]
        if position > 25:
            position = P[len(P) - 1]
        P.append(position)
        if position == 25:
            return turns

In [91]:
SandL()

7

In [94]:
a = [SandL() for i in range(10000)]

In [95]:
sum(a)/10000

12.2711

Average of about 12 turns to finsh the game

In [96]:
plt.hist(a,density=True,bins=15)

(array([3.42461538e-02, 7.57384615e-02, 5.68384615e-02, 3.54923077e-02,
        1.43538462e-02, 7.03846154e-03, 4.22307692e-03, 1.22307692e-03,
        7.61538462e-04, 4.84615385e-04, 1.84615385e-04, 6.92307692e-05,
        0.00000000e+00, 9.23076923e-05, 2.30769231e-05]),
 array([ 2.        ,  6.33333333, 10.66666667, 15.        , 19.33333333,
        23.66666667, 28.        , 32.33333333, 36.66666667, 41.        ,
        45.33333333, 49.66666667, 54.        , 58.33333333, 62.66666667,
        67.        ]),
 <a list of 15 Patch objects>)

<font color='red'>Great work and I am glad to see that you added a histogram.</font>